stages:
  - test

test_orbitmaster:
  stage: test
  image: python:3.9
  before_script:
    - pip install --upgrade pip
    - pip install pytest numpy scipy matplotlib
  script:
    - pytest -v test_orbitmaster_final.py
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - .pytest_cache/
